export const colors = {
	blue: [
		'var(--color-base-blue-50)',
		'var(--color-base-blue-100)',
		'var(--color-base-blue-200)',
		'var(--color-base-blue-300)',
		'var(--color-base-blue-400)',
		'var(--color-base-blue-500)',
		'var(--color-base-blue-600)',
		'var(--color-base-blue-700)',
		'var(--color-base-blue-800)',
		'var(--color-base-blue-900)',
	] as const,
	indigo: [
		'var(--color-base-indigo-50)',
		'var(--color-base-indigo-100)',
		'var(--color-base-indigo-200)',
		'var(--color-base-indigo-300)',
		'var(--color-base-indigo-400)',
		'var(--color-base-indigo-500)',
		'var(--color-base-indigo-600)',
		'var(--color-base-indigo-700)',
		'var(--color-base-indigo-800)',
		'var(--color-base-indigo-900)',
	] as const,
	slate: [
		'var(--color-base-slate-50)',
		'var(--color-base-slate-100)',
		'var(--color-base-slate-200)',
		'var(--color-base-slate-300)',
		'var(--color-base-slate-400)',
		'var(--color-base-slate-500)',
		'var(--color-base-slate-600)',
		'var(--color-base-slate-700)',
		'var(--color-base-slate-800)',
		'var(--color-base-slate-900)',
	] as const,
	gray: [
		'var(--color-base-gray-50)',
		'var(--color-base-gray-100)',
		'var(--color-base-gray-200)',
		'var(--color-base-gray-300)',
		'var(--color-base-gray-400)',
		'var(--color-base-gray-500)',
		'var(--color-base-gray-600)',
		'var(--color-base-gray-700)',
		'var(--color-base-gray-800)',
		'var(--color-base-gray-900)',
	] as const,
	green: [
		'var(--color-base-green-50)',
		'var(--color-base-green-100)',
		'var(--color-base-green-200)',
		'var(--color-base-green-300)',
		'var(--color-base-green-400)',
		'var(--color-base-green-500)',
		'var(--color-base-green-600)',
		'var(--color-base-green-700)',
		'var(--color-base-green-800)',
		'var(--color-base-green-900)',
	] as const,
	emerald: [
		'var(--color-base-emerald-50)',
		'var(--color-base-emerald-100)',
		'var(--color-base-emerald-200)',
		'var(--color-base-emerald-300)',
		'var(--color-base-emerald-400)',
		'var(--color-base-emerald-500)',
		'var(--color-base-emerald-600)',
		'var(--color-base-emerald-700)',
		'var(--color-base-emerald-800)',
		'var(--color-base-emerald-900)',
	] as const,
	amber: [
		'var(--color-base-amber-50)',
		'var(--color-base-amber-100)',
		'var(--color-base-amber-200)',
		'var(--color-base-amber-300)',
		'var(--color-base-amber-400)',
		'var(--color-base-amber-500)',
		'var(--color-base-amber-600)',
		'var(--color-base-amber-700)',
		'var(--color-base-amber-800)',
		'var(--color-base-amber-900)',
	] as const,
	orange: [
		'var(--color-base-orange-50)',
		'var(--color-base-orange-100)',
		'var(--color-base-orange-200)',
		'var(--color-base-orange-300)',
		'var(--color-base-orange-400)',
		'var(--color-base-orange-500)',
		'var(--color-base-orange-600)',
		'var(--color-base-orange-700)',
		'var(--color-base-orange-800)',
		'var(--color-base-orange-900)',
	] as const,
	red: [
		'var(--color-base-red-50)',
		'var(--color-base-red-100)',
		'var(--color-base-red-200)',
		'var(--color-base-red-300)',
		'var(--color-base-red-400)',
		'var(--color-base-red-500)',
		'var(--color-base-red-600)',
		'var(--color-base-red-700)',
		'var(--color-base-red-800)',
		'var(--color-base-red-900)',
	] as const,
	rose: [
		'var(--color-base-rose-50)',
		'var(--color-base-rose-100)',
		'var(--color-base-rose-200)',
		'var(--color-base-rose-300)',
		'var(--color-base-rose-400)',
		'var(--color-base-rose-500)',
		'var(--color-base-rose-600)',
		'var(--color-base-rose-700)',
		'var(--color-base-rose-800)',
		'var(--color-base-rose-900)',
	] as const,
	purple: [
		'var(--color-base-purple-50)',
		'var(--color-base-purple-100)',
		'var(--color-base-purple-200)',
		'var(--color-base-purple-300)',
		'var(--color-base-purple-400)',
		'var(--color-base-purple-500)',
		'var(--color-base-purple-600)',
		'var(--color-base-purple-700)',
		'var(--color-base-purple-800)',
		'var(--color-base-purple-900)',
	] as const,
	violet: [
		'var(--color-base-violet-50)',
		'var(--color-base-violet-100)',
		'var(--color-base-violet-200)',
		'var(--color-base-violet-300)',
		'var(--color-base-violet-400)',
		'var(--color-base-violet-500)',
		'var(--color-base-violet-600)',
		'var(--color-base-violet-700)',
		'var(--color-base-violet-800)',
		'var(--color-base-violet-900)',
	] as const,
	cyan: [
		'var(--color-base-cyan-50)',
		'var(--color-base-cyan-100)',
		'var(--color-base-cyan-200)',
		'var(--color-base-cyan-300)',
		'var(--color-base-cyan-400)',
		'var(--color-base-cyan-500)',
		'var(--color-base-cyan-600)',
		'var(--color-base-cyan-700)',
		'var(--color-base-cyan-800)',
		'var(--color-base-cyan-900)',
	] as const,
	teal: [
		'var(--color-base-teal-50)',
		'var(--color-base-teal-100)',
		'var(--color-base-teal-200)',
		'var(--color-base-teal-300)',
		'var(--color-base-teal-400)',
		'var(--color-base-teal-500)',
		'var(--color-base-teal-600)',
		'var(--color-base-teal-700)',
		'var(--color-base-teal-800)',
		'var(--color-base-teal-900)',
	] as const,
};
